### ISSUE TITLE
Favicon not displayed

### ISSUE THREAD

**Issue by xnmdyjj** [EmielH/tale-hugo#10]
The favicon will not displayed when deployed to github pages.

I checked the source code of html:

link rel="icon" type="image/png" sizes="16x16" href="https://81app.github.ioimages/favicon-16x16.png"

**Comment by EmielH** [comment]
Thanks for letting me know! I just pushed a commit that should solve this issue. Could you check this?

**Comment by xnmdyjj** [comment]
yeah, it's fixed, thank you.
