### ISSUE TITLE
No background color

### ISSUE THREAD

**Issue by tastytea** [EmielH/tale-hugo#14]
A foreground-color is defined but no background-color.

![screenshot_2019-02-08t02 09 05](https://user-images.githubusercontent.com/3681516/52453243-4cebcf80-2b3e-11e9-91b4-7dd822352cca.png)

**Comment by EmielH** [comment]
Hi @tastytea, I've never seen this happen before, do you have a site that I can look at to see what is happening? Or does your browser have a dark background by default?

**Comment by tastytea** [comment]
https://themes.gohugo.io/theme/tale-hugo/ 
My browser has a dark background and a light text color by default.

**Comment by EmielH** [comment]
Thanks for letting me know! I'll fix it by adding a background color. I don't have much time the next few days, though, so I can't make promises when it will be fixed, but feel free to submit a PR. 🙂

**Comment by EmielH** [comment]
@tastytea Could you verify that my commit solves your problem? I'm working on getting the failing build up and running again; it fails due to an error that is unrelated to this issue.

**Comment by tastytea** [comment]
Problem solved, thank you!
