### ISSUE TITLE
How can I change the fonts?

### ISSUE THREAD

**Issue by hadisinaee** [EmielH/tale-hugo#16]
Hi,

Is it possible to customize the fonts? I tried with customized CSS param but I couldn't get any result?

Thanks

**Comment by EmielH** [comment]
Hi @hadisinaee, please see [the documentation](https://github.com/EmielH/tale-hugo#additional-css-files) on using custom CSS files. Basically, you need to create your own CSS file, put that in the `/static` folder of your site and add the filename to the parameter.
