### ISSUE TITLE
Configuring number of lines in preview

### ISSUE THREAD

**Issue by hadisinaee** [EmielH/tale-hugo#17]
Hi,

Is it possible to configure the number of lines to be shown in a post preview? I mean something like this:

```
# config.toml
[param]
   LinesPreview=3
```

**Comment by EmielH** [comment]
Hi @hadisinaee, thank you for using Tale!

Your request is called line clamping. It is not part of the official CSS standard and [most browsers do not support it](https://caniuse.com/#feat=css-line-clamp). Therefore this will not be included in this theme. You can find some additional information in [this article](https://css-tricks.com/line-clampin/). If you don't mind the poor browser support, you could try adding it in your own CSS.
