### ISSUE TITLE
Updated home page behavior with Hugo v >=0.58

### ISSUE THREAD

**Issue by deniskyashif** [EmielH/tale-hugo#28]
`hugo server`
> Building sites … WARN 2019/09/23 13:33:41 In the next Hugo version (0.58.0) we will change how $home.Pages behaves. If you want to list all regular pages, replace .Pages or .Data.Pages with .Site.RegularPages in your home page template.

After updating hugo to v >= 0.58, the home page lists the top level pages, instead of the ones in /content/posts. Changing

```diff
-{{ range (.Paginate .Pages).Pages }}
+{{ range .Site.RegularPages }}
```

in /layouts/index.html preserves the existing behavior.

**Update:** To preserve the paginanion
```html
{{ $paginator := .Paginate (.Site.RegularPages) }}
<div class="catalogue">
    {{ range $paginator.Pages }}
        {{ .Render "summary" }}
    {{ end }}
</div>
```

**Comment by hitdependency** [comment]
You are a saviour. I was looking for a solution for several hours

**Comment by EmielH** [comment]
Hi @deniskyashif, thanks for bringing this to my attention! I will update the theme as soon as possible.

**Comment by EmielH** [comment]
Could you check if the current version of the theme solves this problem? Thanks a lot!

**Comment by deniskyashif** [comment]
> Could you check if the current version of the theme solves this problem? Thanks a lot!

Yes, it works. Thanks for the fix!
