### ISSUE TITLE
Local fonts do not load when site published to subdirectory

### ISSUE THREAD

**Issue by dotnetjunkie** [EmielH/tale-hugo#34]
I'm very happy with the introduction of the GDPR-compliant update in #30, which was something that I, up until now, implemented myself by overriding the default template. Unfortunately, the `fonts.css` requires the `fonts` folder to be located in the domain's root, which is not always the case. My blog, for instance, publishes the blog to /steven.

I believe that the fix is simple. Just change all urls in the `fonts.css` from `/fonts/libre...` to `../fonts/libre...`.

Example:

Current css:

`url('/fonts/libre-baskerville-v7-latin-regular.eot?#iefix') format('embedded-opentype'), /* IE6-IE8 */`

Needed css:

`url('../fonts/libre-baskerville-v7-latin-regular.eot?#iefix') format('embedded-opentype'), /* IE6-IE8 */`

If you like, I can create a PR for you.

**Comment by EmielH** [comment]
Apologies for my late response! I can see the problem, but I wonder if the nesting could also be deeper than one level. This would make `../` not work either. Maybe it would be useful to use the [base URL element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base)?

**Comment by dotnetjunkie** [comment]
> but I wonder if the nesting could also be deeper than one level.

It was my understanding that the `../` in a css would always be relative to the location of the css. And I also assume that the relativiness between css and font files is always the same, because of the way the Tale template is structured. But I could very well be wrong in both cases.

> Maybe it would be useful to use the base URL element?

This is unfortunately outside my scope of expertise. I know too little (meaning: nothing) about the base url, how to apply that in the css, and what the negative consequences of that could be.

**Comment by EmielH** [comment]
You are completely correct, I was thinking of relative URL's in the documents `<head>` tag. My bad!

Your proposed solution appears to work flawlessly in my tests. I just pushed a commit that should solve your problem. Please let me know whether it does!

**Comment by dotnetjunkie** [comment]
I pushed the changes to [my blog](https://blogs.cuttingedge.it/steven/), and I can confirm, this works like a charm. 

Thank you for developing and maintaining this theme. I know from experience how much work it is to maintain stuff.

**Comment by EmielH** [comment]
Glad it works! Thanks for your kind words! Again, apologies that it took me a little while to respond at first.
