### ISSUE TITLE
Adding standalone pages

### ISSUE THREAD

**Issue by diehl** [EmielH/tale-hugo#41]
Hello, 

I'm interested in adding additional pages to my site that one navigates to from the header of the page, similar to an About page. Can you provide additional guidance on how to achieve that? All my attempts have failed so far. My pages are showing up as additional blog posts. 

Thanks!

**Comment by EmielH** [comment]
Hi!

My apologies for the late response! You should be able to create additional pages and link to them, e.g. in the menu, just like the about page. If you make sure they're not in the posts directory, they shouldn't show up as blog posts.

**Comment by diehl** [comment]
Thanks! It took a little more work than expected. Here's the solution I managed to patch together with guidance elsewhere.
https://discourse.gohugo.io/t/tale-theme-creating-a-standalone-page/29359/20

**Comment by EmielH** [comment]
Thanks for getting back to me! I'll investigate if this is something that the theme should facilitate so it's easier to add regular pages.

**Comment by diehl** [comment]
Sure thing! There's definitely room for improvement I believe, unless I missed something. I created a template for regular pages that removed author references. Putting that into the default template would be great!
