### ISSUE TITLE
[Suggest][How to] How can i actually add font awsome previous the name.

### ISSUE THREAD

**Issue by ghost** [EmielH/tale-hugo#46]
Hi there. Thanks for the good theme you made it. I really like it. But you got anyway to add icon before the menu text?
I was trying to add some font-awesome icon but luck. :D 
![image](https://user-images.githubusercontent.com/76900905/104117829-ed645300-5356-11eb-86f5-f4b69476a9dd.png)

**Comment by EmielH** [comment]
You'd need to include the Font Awesome CSS-files as well. This is not included with the theme. When you've included the CSS-files, you can add them using the description [here](https://github.com/EmielH/tale-hugo#additional-css-files).

**Comment by ghost** [comment]
ah ok thanks you :D I'm fixed already. Thanks for the theme by the way :D :D
