### ISSUE TITLE
Google Analytics not working

### ISSUE THREAD

**Issue by cloudlena** [EmielH/tale-hugo#48]
We have recently switched https://github.com/bespinian/blog to this theme and are very happy with it. However, Google Analytics stopped to work. Does Tale officially support Google Analytics or can we add that as a feature?

**Comment by EmielH** [comment]
Thanks for your kind words!

There's no built-in feature for Google Analytics (i.e. just add your id and you're set), but it should work perfectly fine if you add the code into one of the placholder partials. Could you tell me what is happening? Do you receive an error message?

**Comment by elessar-ch** [comment]
Hugo has internal templates for Google Analytics, which should preferably be added in the `<head>` tag.
- https://gohugo.io/templates/internal#google-analytics
- https://developers.google.com/analytics/devguides/collection/analyticsjs

In my opinion, this would be beneficial to do in the Tale template.

**Comment by EmielH** [comment]
Thank you very much for the pull request! I merged it into master and released a new version just now. @mastertinner, could you let me know if this solves your problem?

**Comment by cloudlena** [comment]
It does. Thanks a lot for the great work, @elessar-ch and @EmielH!
