### ISSUE TITLE
Posts summary alignment issue ? 

### ISSUE THREAD

**Issue by plfbvr** [EmielH/tale-hugo#9]
Hi @EmielH

Posts (on the summary page) seems to be aligned one next to the other, instead of one above the other when the post short text is too... short.

I locally fixed the problem fixed by adding a `<br/>` at the end of ` layout/_default/summary.html` but I don't know if it's the right thing to do...

Thanks :)

**Comment by EmielH** [comment]
Hi @plefebvre91, do you perhaps have a screenshot of this happening? Thanks!

**Comment by plfbvr** [comment]
Yep : 

![capture](https://user-images.githubusercontent.com/4353672/49179989-d79c9b00-f353-11e8-8d93-f5aa2ca2001a.png)

Or with a little more text :
![capture](https://user-images.githubusercontent.com/4353672/49180198-45e15d80-f354-11e8-8674-f852502fa02c.png)

**Comment by EmielH** [comment]
Thanks for letting me know about this! I just committed a fix for this issue. Could you check whether it solves your problem?

**Comment by plefebvre91** [comment]
It works :+1:

**Comment by plfbvr** [comment]
It works :+1:
